// scaffolds/frontend/react/files/src/pages/Home.tsx
import { useState } from 'react'
import reactLogo from '../assets/react.svg'
import '../App.css'

function Home() {
  const [count, setCount] = useState(0)

  return (
    <div className="home">
      <header className="home-header">
        <img src={reactLogo} className="logo react" alt="React logo" />
        <h1>{{ name }}</h1>
        <p>{{ description }}</p>
        <div className="card">
          <button onClick={() => setCount((c) => c + 1)}>
            count is {count}
          </button>
        </div>
      </header>
    </div>
  )
}

export default Home

// scaffolds/frontend/angular/files/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent {
  count = 0

  increment() {
    this.count++
  }
}

<div class="home">
  <h1>{{ name }}</h1>
  <p>{{ description }}</p>
  <div class="card">
    <button (click)="increment()">count is {{ count }}</button>
  </div>
</div>
