// scaffolds/components/express/files/Button.jsx
import React from 'react'

export default function Button({ children, variant = 'primary', onClick, type = 'button', disabled = false }) {
  const baseStyles = {
    padding: '0.6em 1.2em',
    borderRadius: '8px',
    border: '1px solid transparent',
    fontSize: '1em',
    fontWeight: 500,
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.6 : 1,
    transition: 'border-color 0.25s, background-color 0.25s',
  }

  const variants = {
    primary: { backgroundColor: '#646cff', color: '#fff' },
    secondary: { backgroundColor: '#213547', color: '#fff' },
    outline: { backgroundColor: 'transparent', border: '1px solid #646cff', color: '#646cff' },
    ghost: { backgroundColor: 'transparent', color: '#213547' },
  }

  const style = { ...baseStyles, ...variants[variant] || variants.primary }

  return (
    <button type={type} onClick={onClick} disabled={disabled} style={style}>
      {children}
    </button>
  )
}

// scaffolds/components/vue/files/Button.vue
<script setup>
defineProps({
  variant: { type: String, default: 'primary' },
  disabled: { type: Boolean, default: false },
})

defineEmits(['click'])
</script>

<template>
  <button
    :class="['btn', `btn--${variant}`, { 'btn--disabled': disabled }]"
    :disabled="disabled"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>

<style scoped>
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.6em 1.2em;
  border-radius: 8px;
  border: 1px solid transparent;
  font-size: 1em;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.25s;
}
.btn--disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.btn--primary {
  background-color: #646cff;
  color: #fff;
}
.btn--secondary {
  background-color: #213547;
  color: #fff;
}
.btn--outline {
  background: transparent;
  border-color: #646cff;
  color: #646cff;
}
.btn--ghost {
  background: transparent;
  color: #213547;
}
.btn--danger {
  background-color: #dc2626;
  color: #fff;
}
.btn--primary:hover { background-color: #535bf2; }
.btn--secondary:hover { background-color: #1a2a38; }
.btn--outline:hover { background-color: #f0f0ff; }
.btn--ghost:hover { background-color: #f0f0f0; }
.btn--danger:hover { background-color: #b91c1c; }
</style>
