// scaffolds/components/react/files/Button.jsx
import React from 'react'

export default function Button({ children, variant = 'primary', onClick, type = 'button', disabled = false, className }) {
  const base = 'inline-flex items-center justify-center rounded-lg px-4 py-2 text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2'
  const variants = {
    primary: 'bg-indigo-600 text-white hover:bg-indigo-700 focus:ring-indigo-500',
    secondary: 'bg-gray-800 text-white hover:bg-gray-900 focus:ring-gray-700',
    outline: 'border border-indigo-600 text-indigo-600 hover:bg-indigo-50 focus:ring-indigo-500',
    ghost: 'text-gray-700 hover:bg-gray-100 focus:ring-gray-500',
    danger: 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500',
  }

  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className={`${base} ${variants[variant] || variants.primary} ${disabled ? 'opacity-50 cursor-not-allowed' : ''} ${className || ''}`}
    >
      {children}
    </button>
  )
}

// scaffolds/components/vue/files/Button.vue
<script setup>
defineProps({
  variant: { type: String, default: 'primary' },
  disabled: { type: Boolean, default: false },
})

defineEmits(['click'])
</script>

<template>
  <button
    :class="['btn', `btn--${variant}`, { 'btn--disabled': disabled }]"
    :disabled="disabled"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>

<style scoped>
.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.6em 1.2em;
  border-radius: 8px;
  border: 1px solid transparent;
  font-size: 1em;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.25s;
}
.btn--disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.btn--primary {
  background-color: #646cff;
  color: #fff;
}
.btn--secondary {
  background-color: #213547;
  color: #fff;
}
.btn--outline {
  background: transparent;
  border-color: #646cff;
  color: #646cff;
}
.btn--ghost {
  background: transparent;
  color: #213547;
}
.btn--danger {
  background-color: #dc2626;
  color: #fff;
}
.btn--primary:hover { background-color: #535bf2; }
.btn--secondary:hover { background-color: #1a2a38; }
.btn--outline:hover { background-color: #f0f0ff; }
.btn--ghost:hover { background-color: #f0f0f0; }
.btn--danger:hover { background-color: #b91c1c; }
</style>
