// scaffolds/frontend/solidstart/files/src/routes/index.tsx
import { Title } from '@solidjs/meta'
import { createSignal } from 'solid-js'

export default function Home() {
  const [count, setCount] = createSignal(0)

  return (
    <main>
      <Title>{{ name }}</Title>
      <div class="home">
        <h1>{{ name }}</h1>
        <p>{{ description }}</p>
        <div class="card">
          <button onclick={() => setCount((c) => c + 1)}>
            count is {count()}
          </button>
        </div>
      </div>
    </main>
  )
}

// scaffolds/frontend/qwik/files/src/routes/index.tsx
import { component$, useSignal } from '@builder.io/qwik'
import type { DocumentHead } from '@builder.io/qwik-city'

export default component$(() => {
  const count = useSignal(0)

  return (
    <div class="home">
      <h1>{{ name }}</h1>
      <p>{{ description }}</p>
      <div class="card">
        <button onClick$={() => count.value++}>
          count is {count.value}
        </button>
      </div>
    </div>
  )
})

export const head: DocumentHead = {
  title: '{{ name }}',
  meta: [{ name: 'description', content: '{{ description }}' }],
}
